version: '3.9'
name: 'streetside-ms-arch'

services:
  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - '3000:3000'
    depends_on:
      - listings-service
      - reviews-service
      - auth-service
      - messaging-service
    networks:
      - skynet

  # Laurie's Services
  listings-service:
    build:
      context: ./listing-service
    container_name: listing-service
    ports:
      - '3001:3000'
    networks:
      - skynet

  messaging-service:
    build:
      context: ./messaging-service
    container_name: messaging-service
    depends_on:
      - mongodb
    ports:
      - '3004:3000'
    networks:
      - skynet

  reviews-service:
    build:
      context: ./reviews-service
    container_name: reviews-service
    ports:
      - '3002:3000'
    networks:
      - skynet

  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    depends_on:
      - mongodb
    ports:
      - '3003:3000'
    environment:
      - JWT_SECRET=supersecretkey
    networks:
      - skynet

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - '27017:27017'
    networks:
      - skynet

networks:
  skynet:
    driver: bridge
