services:
  api-gateway:
    build:
      context: ./frontend
    ports:
      - '8080:8080'
    depends_on:
      - messages
    networks:
      - app-network

  messages:
    build:
      context: ./backend/messages
    ports:
      - '3004:3004'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
