name: frontend-linter

# when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# This workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # the singular "lint" job
  lint:
    # the type of runner that the job will run on
    runs-on: ubuntu-latest
    # the sequence of tasks that will be executed
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'
      - name: Install Dependencies
        run: npm ci # faster and more reliable for CI than npm i
      - name: Run ESLint
        run: npx eslint . --max-warnings=0 # no warnings allowed
      - name: Run Prettier
        run: npx prettier --check . # check if files are properly formatted
